- name: Crear {{ deploy_dir }}
  ansible.builtin.file:
    path: "{{ deploy_dir }}"
    state: directory
    mode: "0755"

- name: Copiar docker-compose.yml y .env
  ansible.builtin.copy:
    src: "{{ stack_src_dir }}/{{ item.src }}"
    dest: "{{ deploy_dir }}/{{ item.dest }}"
    mode: "0644"
  loop:
    - { src: "docker-compose.yml", dest: "docker-compose.yml" }
    - { src: ".env.example",       dest: ".env" }

- name: Inyectar variables en .env
  ansible.builtin.lineinfile:
    path: "{{ deploy_dir }}/.env"
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
    create: yes
  loop:
    - { key: "WG_HOST",     value: "{{ wg_public_host }}" }
    - { key: "WG_PORT",     value: "{{ wg_port }}" }
    - { key: "WG_SUBNET",   value: "{{ wg_subnet }}" }
    - { key: "WG_DNS",      value: "{{ wg_dns }}" }
    - { key: "JWT_SECRET",  value: "{{ jwt_secret }}" }
    - { key: "TOTP_ISSUER", value: "AutoVPN" }
    - { key: "TZ",          value: "{{ timezone | default('UTC') }}" }

- name: Levantar stack
  ansible.builtin.shell: docker compose up -d
  args:
    chdir: "{{ deploy_dir }}"
