version: '3.8'
services:
  backend:
    build:
      context: ../../../../backend  # Ruta relativa desde docker-compose al Dockerfile
    container_name: autovpn-backend
    ports:
      - "8000:8000"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host
    environment:
      - SERVER_PUBLIC_KEY=${SERVER_PUBLIC_KEY}

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SERVERURL=13.61.61.208
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - /lib/modules:/lib/modules
      - /etc/wireguard:/etc/wireguard

    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
