# Asegurar prerequisitos
- name: Paquetes base para APT/clave
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

# Preparar keyring
- name: Crear directorio keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

# Descargar y dearmar la clave de Docker (binaria .gpg)
- name: Descargar clave GPG de Docker (binaria)
  ansible.builtin.shell: |
    set -euo pipefail
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    executable: /bin/bash
    creates: /etc/apt/keyrings/docker.gpg

# Asegurar permisos legibles por APT
- name: Permisos del keyring de Docker
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'

# Añadir repo Docker CE (usando el codename del sistema, p.ej. noble)
- name: Registrar repositorio Docker CE (estable)
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ (ansible_architecture == 'x86_64') | ternary('amd64', ansible_architecture) }}
      signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }} stable
    filename: docker
    state: present
    update_cache: yes

# Instalar Docker + plugin compose
- name: Instalar Docker CE + compose plugin
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

# (Opcional) añadir usuario 'ubuntu' al grupo docker
- name: Añadir ubuntu a grupo docker
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes

# Habilitar y arrancar Docker
- name: Habilitar y arrancar Docker
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started

